sudo: required

language: cpp
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - clang-10
    - libx11-dev
    - libgl1-mesa-dev
    - liblo-dev
    - libjack-dev
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64

jobs:
  include:
  - name: "Linux (GCC)"
    env: LINUX=true BUILD_DSSI=true CC=gcc CXX=g++

  - name: "Linux (Clang)"
    env: LINUX=true BUILD_DSSI=true CC=clang-10 CXX=clang++-10

  - name: "Windows (MinGW)"
    env: WIN32=true BUILD_DSSI=false

script: ./plugins/wolf-shaper/Common/Utils/make_release.sh

notifications:
  email:
    on_success: never
    on_failure: change
