sudo: required

language: cpp
compiler: gcc
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - libx11-dev
    - libgl1-mesa-dev
    - liblo-dev
    - libjack-dev
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
script:
  - make release
