sudo: required

language: cpp
compiler: gcc
dist: bionic
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - clang-10
    - libx11-dev
    - libgl1-mesa-dev
    - liblo-dev
    - libjack-dev
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
script:
  - LINUX=true BUILD_DSSI=true CC=gcc CXX=g++ ./plugins/wolf-shaper/Common/Utils/make_release.sh
  - LINUX=true BUILD_DSSI=true CC=clang-10 CXX=clang++-10 ./plugins/wolf-shaper/Common/Utils/make_release.sh
  - WIN32=true BUILD_DSSI=false ./plugins/wolf-shaper/Common/Utils/make_release.sh
