name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt update
        sudo apt install libx11-dev libgl1-mesa-dev liblo-dev libjack-dev
    - run: CC=gcc CXX=g++ make
    - run: make clean
    - run: CC=clang CXX=clang++ make
